name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: dotnettkxel.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t dotnettkxel.azurecr.io/dotnet2 .
          docker tag dotnettkxel.azurecr.io/dotnet2:latest dotnettkxel.azurecr.io/dotnet2
          docker push dotnettkxel.azurecr.io/dotnet2
